"""add unique constraint to permissions

Revision ID: 75c53aa1c97b
Revises: c6b2591fc473
Create Date: 2026-09-07 22:29:17.189045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c53aa1c97b'
down_revision: Union[str, Sequence[str], None] = 'c6b2591fc473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_permission_user_workspace_file_group', 'permissions', ['user_id', 'workspace_id', 'file_group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_permission_user_workspace_file_group', 'permissions', type_='unique')
    # ### end Alembic commands ###
