"""create admin setup requests

Revision ID: 82be27034fb4
Revises: 4d7a2bab2eb1
Create Date: 2026-09-06 22:08:12.584875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82be27034fb4'
down_revision: Union[str, Sequence[str], None] = '4d7a2bab2eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_setup_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='admin_setup_request_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_setup_requests_email'), 'admin_setup_requests', ['email'], unique=False)
    op.create_index(op.f('ix_admin_setup_requests_status'), 'admin_setup_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_setup_requests_status'), table_name='admin_setup_requests')
    op.drop_index(op.f('ix_admin_setup_requests_email'), table_name='admin_setup_requests')
    op.drop_table('admin_setup_requests')
    # ### end Alembic commands ###
