"""create data source credentials

Revision ID: c4ef4213ce20
Revises: 75c53aa1c97b
Create Date: 2026-09-07 22:45:50.714061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ef4213ce20'
down_revision: Union[str, Sequence[str], None] = '75c53aa1c97b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('MYSQL', 'POSTGRESQL', 'MSSQL', 'SNOWFLAKE', 'AWS_S3', 'AZURE_BLOB', name='data_source_type'), nullable=False),
    sa.Column('encrypted_config', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_credentials_created_by'), 'data_source_credentials', ['created_by'], unique=False)
    op.create_index(op.f('ix_data_source_credentials_name'), 'data_source_credentials', ['name'], unique=False)
    op.create_index(op.f('ix_data_source_credentials_source_type'), 'data_source_credentials', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_source_credentials_source_type'), table_name='data_source_credentials')
    op.drop_index(op.f('ix_data_source_credentials_name'), table_name='data_source_credentials')
    op.drop_index(op.f('ix_data_source_credentials_created_by'), table_name='data_source_credentials')
    op.drop_table('data_source_credentials')
    # ### end Alembic commands ###
